[package]
name = "bytesize"
description = "ByteSize is an utility that easily makes bytes size representation and helps its arithmetic operations."
version = "0.0.1"
authors = ["Hyunsik Choi <hyunsik.choi at gmail dot com>"]

readme = "README.md"
keywords = ["bytes", "utility"]
license = "Apache-2.0"